# Build customization
project_name: kanister
builds:
  - main:  cmd/kanctl/main.go
    binary: kanctl
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - main:  cmd/kando/main.go
    binary: kando
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

# Archive customization
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
