# Build customization
project_name: kanister
builds:
  - main:  cmd/kanctl/main.go
    binary: kanctl
    ldflags:
      - -s -w -X github.com/kanisterio/kanister/pkg/version.VERSION={{.Version}} -X github.com/kanisterio/kanister/pkg/version.GIT_COMMIT={{.Commit}} -X github.com/kanisterio/kanister/pkg/version.BUILD_DATE={{.Date}}
      - ./usemsan=-msan
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - main:  cmd/kando/main.go
    binary: kando
    ldflags:
      - -s -w -X github.com/kanisterio/kanister/pkg/version.VERSION={{.Version}} -X github.com/kanisterio/kanister/pkg/version.GIT_COMMIT={{.Commit}} -X github.com/kanisterio/kanister/pkg/version.BUILD_DATE={{.Date}}
      - ./usemsan=-msan
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

# Archive customization
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
