apiVersion: v1
description: A helm chart to create profile custom resource for kanister
engine: gotpl
name: kanister-profile
version: 0.1.0
maintainers:
  - email: gautham@kasten.io
    name: gauthamsunjay
