apiVersion: v1
description: A helm chart to create profile custom resource for kanister
engine: gotpl
name: profile
version: 0.1.0
maintainers:
  - email: tom@kasten.io
    name: tdmanv
  - email: ilya@kasten.io
    name: depohmel

